name: 🐞 Bug
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please confirm that you have searched for similar issues and discussions before submitting.
      options:
        - label: I have searched for similar issues and discussions
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug Description
      description: Describe the bug in detail, including steps to reproduce, expected behavior, and actual behavior.
      placeholder: |
        1. I called function 'x' with the following arguments...
        2. I expected the result to be...
        3. Instead, the actual result was...
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: System Information
      description: Please run `dp.print_debug_info()` and copy/paste the results here, or manually fill in the values below.
      value: |
        - Datapane version:
        - Python version:
        - Operating System:
        - Using Jupyter: Yes / No
        - Pip or Conda:
        - Dependencies:
          - pandas:
          - ...
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
